### ISSUE TITLE
add backtrace

### ISSUE THREAD

**Issue by 0x6D70** [Lockna/cernel#5]
# Tasks
* [x] print backtrace with raw addresses
* [x] print backtrace with function names
* [x] print backtrace with lines and function names
* [x] is it possible to print parameters for backtrace (maybe tell gcc to place all parameters on the stack, so we can grab them later)

**Comment by 0x6D70** [comment]
Task 3/4 won't be done in the near future, because they are not needed urgently and it is a lot of work to implement it
